---
title: "BC estimates"
format: 
    html:
      embed-resources: true
editor: visual
---

```{r}
library(tidyverse)
library(broom)
library(here)
library(knitr)
```


```{r}

data <- readRDS(here("data/processed/derived_quantities.rds"))

# cleaning -----------------------------------------------------------
data <- data %>%  mutate(species = str_replace_all(species, " ", "_"), # clean species names 
                       sp_region = paste(species, region, sep = "_") 
)

# standardize and calculate anomalies -------------------------------------------------------------
data <- data %>%  group_by(region) %>%  mutate(
  year_c = (year - mean(year, na.rm = TRUE))/10 # center year and scale to decades
)  %>%  ungroup() %>% 
  group_by(sp_region) %>% 
  mutate(across(
    c(cog_y, cog_x, depth_niche, thermal_niche),
    ~ .x - mean(.x, na.rm = TRUE),
    .names = "{.col}_c"
  )) %>% 
  ungroup()

data = data %>% filter(region == 'BC')

```

## Get slopes latitudinal range centroid

```{r}
slopes <- data %>%
  group_by(species) %>%
  do(tidy(lm(cog_y_c ~ 0 + year_c, data = .)))

slopes %>% kable()

# density of slope estimates across spp
ggplot(slopes, aes(x = "", y = estimate)) + 
  geom_boxplot(fill = "skyblue", alpha = 0.6) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(
    y = "Slope (Lat centroid change per decade (km))"
  )
```

