$ENV{'TEXINPUTS'} = './PNAS_stuff//:' . ($ENV{'TEXINPUTS'} // '');
$ENV{'BSTINPUTS'} = './PNAS_stuff//:' . ($ENV{'BSTINPUTS'} // '');
$ENV{'BIBINPUTS'} = './PNAS_stuff//:' . ($ENV{'BIBINPUTS'} // '');
