# Build from this folder. PNAS class/style/bst/logo files live in PNAS_stuff/,
# so point kpathsea at it for LaTeX (.cls/.sty/.ldf) and BibTeX (.bst/.bib).
$do_cd = 1;
$ENV{'TEXINPUTS'} = './PNAS_stuff//:' . ($ENV{'TEXINPUTS'} // '');
$ENV{'BSTINPUTS'} = './PNAS_stuff//:' . ($ENV{'BSTINPUTS'} // '');
$ENV{'BIBINPUTS'} = './:./PNAS_stuff//:' . ($ENV{'BIBINPUTS'} // '');
$pdf_mode = 1;
$bibtex_use = 2;
